#include "menu_api.lua"

function init()
	if GetBool(modid.."startedUsingMenu") == false then
		SetBool(modid.."ingame-menu", true)
		SetFloat(modid.."player-boost-velocity", 0.3)
		SetFloat(modid.."vehicle-boost-velocity", 0.3)
		SetFloat(modid.."free-cam-velocity", 1.0)
		SetFloat(modid.."click-explode-power", 2)
		SetFloat(modid.."click-destroy-power", 5)
		SetFloat(modid.."blast-away-radius", 10)
		SetFloat(modid.."clear-debris-radius", 10)
		SetFloat(modid.."ray-cutter-radius", 0.2)
		SetBool(modid.."startedUsingMenu", true)
	end

	SetBool(tempid.."setting-ingame-menu.key", false)
	SetBool(tempid.."setting-free-cam.key", false)
	SetBool(tempid.."setting-blast-away.key", false)
	SetBool(tempid.."setting-vehicle-boost.key", false)
	SetBool(tempid.."setting-player-boost.key", false)
	SetBool(tempid.."setting-click-fire.key", false)
	SetBool(tempid.."setting-click-explode.key", false)
	SetBool(tempid.."setting-click-delete.key", false)
	SetBool(tempid.."setting-click-destroy.key", false)
	SetBool(tempid.."setting-ray-cutter.key", false)
	SetBool(tempid.."setting-clear-debris.key", false)
	SetBool(tempid.."setting-flight.key", false)
end

function draw()
	UiPush()
		UiTranslate(0, 0)
		UiAlign("left top")
		UiFont("regular.ttf", 26)
		UiText("The Text Button Contains Info About A Module")
		UiTranslate(0, 50)
		UiText("The + Button Contains Settings For A Module. Not All Have Settings")
		UiTranslate(0, 50)
		UiText("The On / Off Button Toggles The Module")
		UiTranslate(0, 50)
		UiFont("bold.ttf", 26)
		UiText("Turning off 'Ingame Menu' will NOT disable other cheats!")
	UiPop()
	UiPush()
		UiTranslate(UiCenter(), 50)
		UiAlign("center middle")
		UiFont("bold.ttf", 48)
		UiColor(1, 1, 1)
		UiText("SirCode's Mod Menu")
		UiFont("regular.ttf", 26)
		UiTranslate(240, 6)
		UiColor(1, 0.8, 0.5)
		UiText("v11")
		UiTranslate(-240, 50)
		UiColor(1, 1, 1)
		UiText("Contact Dominusnak on the Official Teardown Discord for help")
		UiTranslate(0, 50)
		UiText("This mod runs stable on 1.5.1, you are on "..GetString("game.version"))
		UiTranslate(0, 75)
		UiPush()
			UiTranslate(-55, 60)
			DrawCheatButtonSet("Ingame Menu", "ingame-menu", true)
			UiTranslate(-160, 60)
			DrawCheatButtonSet("Freeze Timer", "inf-timer", false)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Infinite Ammo", "inf-ammo", false)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Infinite Health", "inf-health", false)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Free-Camera", "free-cam", true)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Blast Away", "blast-away", true)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Debug Info", "debug-info", false)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Vehicle Boost", "vehicle-boost", true)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Player Boost", "player-boost", true)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Click Fire", "click-fire", true)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Click Explode", "click-explode", true)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Click Delete", "click-delete", true)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Click Destroy", "click-destroy", true)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Unlock Tools", "unlock-tools", false)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Ray Cutter", "ray-cutter", true)
			UiTranslate(-330, 60)
			DrawCheatButtonSet("Clear Debris", "clear-debris", true)
			UiTranslate(330, 0)
			DrawCheatButtonSet("Smooth Flight", "flight", true)
		UiPop()
	UiPop()
	UiPush()
		UiTranslate(UiCenter(), UiHeight() - 80)
		UiAlign("center middle")
		UiFont("regular.ttf", 26)
		UiButtonImageBox("ui/common/box-outline-6.png", 6, 6)
		UiColor(1, 1, 1)
		if UiTextButton("Close", 200, 40) then
			Menu()
			SetBool(tempid.."descOpen", false)
			UiSound("Sounds/BlipHigher.wav")
		end
	UiPop()
	UiPush()
		if GetBool(tempid.."descOpen") then
			UiModalBegin()
			UiTranslate(UiCenter(), UiMiddle())
			UiAlign("center middle")
			if InputDown("esc") then
				SetBool(tempid.."descOpen", false)
			end
			if not UiIsMouseInRect(512, 512) and InputDown("lmb") then
				SetBool(tempid.."descOpen", false)
			end
			UiBlur(1)
			UiColor(0.7, 0.7, 0.7, 0.1)
			UiRect(512, 512)
			UiFont("bold.ttf", 32)
			UiTranslate(0, -200)
			UiColor(1, 1, 1)
			UiText(GetString(tempid.."curToolText").." Information")
			local curMod = GetString(tempid.."curTool")
			if curMod == "ingame-menu" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("An Ingame Mod Menu")
			elseif curMod == "inf-timer" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Freeze / Stop Mission Timer")
			elseif curMod == "inf-ammo" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Unlimited Weapon Ammo")
			elseif curMod == "inf-health" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Unlimited Health / Never Die")
				UiTranslate(0, 50)
				UiText("Taking massive damage can still fake-kill you")
				UiTranslate(0, 50)
				UiText("(You will not teleport, screen will just darken)")
			elseif curMod == "free-cam" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Noclip Flight Mode / Freecam Hack")
				UiTranslate(0, 50)
				UiText("Currently A Little Buggy. Still A WIP Module")
			elseif curMod == "blast-away" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Blow Away Debris And Objects")
			elseif curMod == "debug-info" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Show Metrics And Debug Information")
			elseif curMod == "vehicle-boost" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Hold A Boost Key To Push Your Car In A Direction")
				UiTranslate(0, 50)
				UiText("Hold "..GetString(modid.."vehicle-boost1").." + W/A/S/D To Boost Horizontally")
				UiTranslate(0, 50)
				UiText("Hold "..GetString(modid.."vehicle-boost.key").." + Space/Shift To Boost Vertically")
			elseif curMod == "player-boost" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Hold A Boost Key To Push Your Player In A Direction")
				UiTranslate(0, 50)
				UiText("Hold "..GetString(modid.."player-boost1").." + W/A/S/D To Boost Horizontally")
				UiTranslate(0, 50)
				UiText("Hold "..GetString(modid.."player-boost.key").." + Space/Shift To Boost Vertically")
			elseif curMod == "click-fire" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Place Fire At Mouse Cursor")
				UiTranslate(0, 50)
				UiText("Only Works On Flammable Objects")
			elseif curMod == "click-explode" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Explode Region At Mouse Cursor")
			elseif curMod == "click-delete" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Delete Object Youre Looking At")
			elseif curMod == "click-destroy" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Exploit To Place Larger Explosions At Cursor")
				UiTranslate(0, 50)
				UiText("Only Really Works On Small / Dynamic Objects")
				UiTranslate(0, 50)
				UiText("(Click Explode On Steroids)")
			elseif curMod == "unlock-tools" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Lets You Use Any Tool (Doesnt Edit Savegame)")
			elseif curMod == "ray-cutter" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Cut Holes In The Direction Youre Facing")
			elseif curMod == "clear-debris" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Delete All Nearby Moving / Dynamic Objects In Radius")
			elseif curMod == "flight" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Minecraft-Like Flight Mode, Allows Usage Of Tools While Flying")
			end
			UiModalEnd()
		end
	UiPop()
	UiPush()
		if GetBool(tempid.."settingsOpen") then
			UiModalBegin()
			UiTranslate(UiCenter(), UiMiddle())
			UiAlign("center middle")
			if InputDown("esc") then
				SetBool(tempid.."settingsOpen", false)
			end
			if not UiIsMouseInRect(512, 512) and InputDown("lmb") then
				SetBool(tempid.."settingsOpen", false)
			end
			UiBlur(1)
			UiColor(0.7, 0.7, 0.7, 0.1)
			UiRect(512, 512)
			UiFont("bold.ttf", 32)
			UiTranslate(0, -200)
			UiColor(1, 1, 1)
			UiText(GetString(tempid.."curToolText").." Settings")
			local curMod = GetString(tempid.."curTool")
			if curMod == "ingame-menu" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Toggle Menu")
				UiTranslate(0, 50)
				DrawKeybindSet("ingame-menu", "0")
			elseif curMod == "free-cam" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Activate Free-cam")
				UiTranslate(0, 50)
				DrawKeybindSet("free-cam", "0")
				UiTranslate(0, 75)
				UiText("Free-cam Movespeed")
				UiTranslate(0, 50)
				DrawIncDecSet("free-cam-velocity", 0.1, 0, 2.0)
			elseif curMod == "blast-away" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Use Blast Away")
				UiTranslate(0, 50)
				DrawKeybindSet("blast-away", "0")
				UiTranslate(0, 75)
				UiText("Blast Radius")
				UiTranslate(0, 50)
				DrawIncDecSet("blast-away-radius", 10, 0, 100)
			elseif curMod == "vehicle-boost" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Forward / Reverse Boost")
				UiTranslate(0, 50)
				DrawKeybindSet("vehicle-boost", "1")
				UiTranslate(0, 75)
				UiText("Upward / Downward Boost")
				UiTranslate(0, 50)
				DrawKeybindSet("vehicle-boost", "0")
				UiTranslate(0, 75)
				UiText("Boost Velocity")
				UiTranslate(0, 50)
				DrawIncDecSet("vehicle-boost-velocity", 0.1, 0, 4.0)
			elseif curMod == "player-boost" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Forward / Reverse Boost")
				UiTranslate(0, 50)
				DrawKeybindSet("player-boost", "1")
				UiTranslate(0, 75)
				UiText("Upward / Downward Boost")
				UiTranslate(0, 50)
				DrawKeybindSet("player-boost", "0")
				UiTranslate(0, 75)
				UiText("Boost Velocity")
				UiTranslate(0, 50)
				DrawIncDecSet("player-boost-velocity", 0.1, 0, 4.0)
			elseif curMod == "click-fire" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Click Fire Tool")
				UiTranslate(0, 50)
				DrawToolSelector("click-fire-tool")
			elseif curMod == "click-explode" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Click Explode Tool")
				UiTranslate(0, 50)
				DrawToolSelector("click-explode-tool")
				UiTranslate(0, 75)
				UiText("Explosion Power")
				UiTranslate(0, 50)
				DrawIncDecSet("click-explode-power", 0.1, 0.5, 4.0)
			elseif curMod == "click-delete" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Click Delete Tool")
				UiTranslate(0, 50)
				DrawToolSelector("click-delete-tool")
			elseif curMod == "click-destroy" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Click Destroy Tool")
				UiTranslate(0, 50)
				DrawToolSelector("click-destroy-tool")
				UiTranslate(0, 75)
				UiText("Explosion Power")
				UiTranslate(0, 50)
				DrawIncDecSet("click-destroy-power", 1, 5, 30)
			elseif curMod == "ray-cutter" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Use Ray Cutter")
				UiTranslate(0, 50)
				DrawKeybindSet("ray-cutter", "0")
				UiTranslate(0, 75)
				UiText("Cutter Radius")
				UiTranslate(0, 50)
				DrawIncDecSet("ray-cutter-radius", 0.1, 0, 4.0)
			elseif curMod == "clear-debris" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Use Clear Debris")
				UiTranslate(0, 50)
				DrawKeybindSet("clear-debris", "0")
				UiTranslate(0, 75)
				UiText("Deletion Radius")
				UiTranslate(0, 50)
				DrawIncDecSet("clear-debris-radius", 10, 0, 100)
			elseif curMod == "flight" then
				UiFont("regular.ttf", 26)
				UiTranslate(0, 75)
				UiText("Activate Flight")
				UiTranslate(0, 50)
				DrawKeybindSet("flight", "0")
				UiTranslate(0, 75)
				UiText("Flight Movespeed")
				UiTranslate(0, 50)
				DrawIncDecSet("free-cam-velocity", 0.1, 0, 2.0)
			end
			UiModalEnd()
		end
	UiPush()
end

