#include "menu_api.lua"

function init()
	DebugPrint('Initializing');
	validateDefaultKeys()
	-- if GetBool(modid..'startedUsingMenu') == false then
	-- 	SetBool(modid..'ingame-menu', true)
	-- 	SetFloat(modid..'player-boost-velocity', 0.3)
	-- 	SetFloat(modid..'vehicle-boost-velocity', 0.3)
	-- 	SetFloat(modid..'free-cam-velocity', 1.0)
	-- 	SetFloat(modid..'click-explode-power', 2)
	-- 	SetFloat(modid..'click-destroy-power', 5)
	-- 	SetFloat(modid..'blast-away-radius', 10)
	-- 	SetFloat(modid..'clear-debris-radius', 10)
	-- 	SetFloat(modid..'ray-cutter-radius', 0.2)
	-- 	SetBool(modid..'startedUsingMenu', true)
	-- end

	-- SetBool(tempid..'setting-ingame-menu.key', false)
	-- SetBool(tempid..'setting-free-cam.key', false)
	-- SetBool(tempid..'setting-blast-away.key', false)
	-- SetBool(tempid..'setting-vehicle-boost.key', false)
	-- SetBool(tempid..'setting-player-boost.key', false)
	-- SetBool(tempid..'setting-click-fire.key', false)
	-- SetBool(tempid..'setting-click-explode.key', false)
	-- SetBool(tempid..'setting-click-delete.key', false)
	-- SetBool(tempid..'setting-click-destroy.key', false)
	-- SetBool(tempid..'setting-ray-cutter.key', false)
	-- SetBool(tempid..'setting-clear-debris.key', false)
	-- SetBool(tempid..'setting-flight.key', false)
end

function draw()
	UiPush()
		UiTranslate(0, 0)
		UiAlign('left top')
		UiFont('regular.ttf', 26)
		UiText('The Text Button Contains Info About A Module')
		UiTranslate(0, 50)
		UiText('The + Button Contains Settings For A Module. Not All Have Settings')
		UiTranslate(0, 50)
		UiText('The On / Off Button Toggles The Module')
		UiTranslate(0, 50)
		UiFont('bold.ttf', 26)
		UiText('Turning off "Ingame Menu" will NOT disable other cheats!')
	UiPop()
	UiPush()
		UiTranslate(UiCenter(), 50)
		UiAlign('center middle')
		UiFont('bold.ttf', 48)
		UiColor(1, 1, 1)
		UiText('The Assist Menu')
		UiFont('regular.ttf', 26)
		UiTranslate(240, 6)
		UiColor(1, 0.8, 0.5)
		UiText('v'..version)
		UiTranslate(-240, 50)
		UiColor(1, 1, 1)
		UiText('Contact SirCode on the Teardown Discord for help')
		UiTranslate(0, 50)
		UiText('This mod runs stable on 1.6+, you are on '..GetString('game.version'))
		UiTranslate(0, 75)
	UiPop()
	UiPush()
		UiTranslate(UiCenter(), UiHeight() - 80)
		UiAlign('center middle')
		UiFont('regular.ttf', 26)
		UiButtonImageBox('ui/common/box-outline-6.png', 6, 6)
		UiColor(1, 1, 1)
		if UiTextButton('Close', 200, 40) then
			Menu()
			SetBool(tempid..'descOpen', false)
			UiSound('Sounds/BlipHigher.wav')
		end
	UiPop()
end

